Repository Azure/communication-ui-library-android, pull requests merged in 2022-06, with the labels that each got.

#255 [Feature] Screen adaptiveness for large screens
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/DependencyInjectionContainerHolder.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/grid/ParticipantGridView.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/grid/ParticipantGridViewModel.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/CallingViewModelFactory.kt
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp-land/azure_communication_ui_calling_call_local_pip_video.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp/azure_communication_ui_calling_call_header.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp/azure_communication_ui_calling_call_local_pip_video.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp/azure_communication_ui_calling_fragment_setup.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-sw600dp/azure_communication_ui_calling_integers.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values/azure_communication_ui_calling_attrs.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values/azure_communication_ui_calling_integers.xml
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridCellViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridViewModelUnitTest.kt
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature, GA

#285 [ Bug] Memory leak fixes on AudioSessionManager
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AudioSessionManager.kt
Labels: GA

#313 [Bug] fix occasional NPE with invalid CallEndReason object
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
Labels: bug

#318 [Feature] Allow release and debug variant
  azure-communication-ui/azure-communication-ui-demo-app/build.gradle
Labels: Feature

#323 [Bug] Fix padding issue for draggable PiP to cover RTL scenario
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-land/azure_communication_ui_calling_call_local_pip_video.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp-land/azure_communication_ui_calling_call_local_pip_video.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout-sw600dp/azure_communication_ui_calling_call_local_pip_video.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/layout/azure_communication_ui_calling_call_local_pip_video.xml
Labels: bug

#333 [Bug] Mic permission alert fix
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/PermissionManager.kt
Labels: bug

#335 [Bug] fix jacoco test coverage reporting
  azure-communication-ui/azure-communication-ui/jacoco.gradle
Labels: bug

#296 [Bug] Avatar view fix for unnamed participant in participant list
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/utilities/BottomCellActionViewHolder.kt
Labels: bug

#320 [Bug] Potential memory leak fix for bluetooth pair-unpair scenario
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AudioSessionManager.kt
Labels: bug, Refactor

#366 [Refactor] Wait for join progress indicator to complete when running UI tests
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeNetworkTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/ScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/UiTestUtils.kt
Labels: Refactor

#368 [Bug] Display DrawerDialog across screen rotation
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmView.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participantlist/ParticipantListView.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/common/audiodevicelist/AudioDeviceListView.kt
Labels: bug

#365 [Bug] fix ANR when trying to hang up call on hold
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/VideoViewManager.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/localuser/LocalParticipantView.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/PreviewAreaView.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
Labels: bug

#286 [Bug] fix issue with multiple activity instances
  azure-communication-ui/azure-communication-ui-demo-app/build.gradle
  azure-communication-ui/azure-communication-ui-demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/build.gradle
  azure-communication-ui/scripts/runUiTests.sh
Labels: bug
