Repository Azure/communication-ui-library-android, pull requests merged in 2022-03, with the labels that each got.

#156 [Refactor] Remove generics from error handling public API and rename ErroEvent to CommunicationUIErrorEvent
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivityErrorHandler.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/CallComposite.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/CallingEventHandler.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LanguageCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LocalizationConfiguration.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CallCompositeEventsHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CommunicationUIErrorCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CommunicationUIErrorEvent.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/ErrorEvent.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/CallCompositeError.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/CallStateError.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/FatalError.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/CallingService.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/configuration/CallCompositeEventsHandlerTests.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/reducer/ErrorReducerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/reducer/LocalParticipantReduxStateReducerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/ErrorHandlerUnitTests.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
  docs/api/CallComposite/classes/CallComposite.md
  docs/api/CallComposite/interfaces/CallingEventHandler.md
Labels: Task

#159 [Bug] Fixed title bar focus order
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeAudioDeviceListTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/matchers/BottomCellViewHolderMatcher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/ScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/UiTestUtils.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/SetupFragment.kt
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_fragment_setup.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-night/azure_communication_ui_colors.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_colors.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_themes.xml
  azure-communication-ui/scripts/runUiTests.sh
Labels: bug

#86 [Feature] Reduce app size using Android R8
  azure-communication-ui/azure-communication-ui-demo-app/acs-ui-library.pro
  azure-communication-ui/azure-communication-ui-demo-app/build.gradle
  azure-communication-ui/azure-communication-ui-demo-app/proguard-rules.pro
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/strings.xml
  azure-communication-ui/azure-communication-ui/build.gradle
  azure-communication-ui/azure-communication-ui/consumer-rules.pro
  azure-communication-ui/build.gradle
  azure-communication-ui/scripts/installAab.sh
Labels: Feature
