Repository Azure/communication-ui-library-android, pull requests merged in 2022-08, with the labels that each got.

#389 [Feature] Dispatch cameraFailure error to subscribers
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/models/CallCompositeErrorCode.java
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature

#386 [Feature] Custom Named Exception
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/CallCompositeException.java
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/DependencyInjectionContainerHolder.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/manager/AudioSessionManager.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/redux/AppStore.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/configuration/CallCompositeExceptionTest.kt
Labels: Feature

#385 [Feature] Receive error event when device manager throws any error
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorCode.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/models/CallCompositeErrorCode.java
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/redux/action/LocalParticipantAction.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/CallingService.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
Labels: Feature

#396 [Refactor] CallCompositeException should extend AzureException
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/CallCompositeException.java
Labels: Refactor

#390 [Feature] Open OS settings permission menu via shortcut button
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/PermissionWarningView.kt
  azure-communication-ui/azure-communication-ui/src/calling/res/layout/azure_communication_ui_calling_fragment_setup.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-de-rDE/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-de/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-en-rGB/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-es-rES/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-es/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-fr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-it-rIT/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-it/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ja/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ko/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-nl/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-pt/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ru/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-tr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values/azure_communication_ui_calling_strings.xml
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature

#404 [Chat][Feature] add chat module
  azure-communication-ui/chat/.gitignore
  azure-communication-ui/chat/build.gradle
  azure-communication-ui/chat/consumer-rules.pro
  azure-communication-ui/chat/proguard-rules.pro
  azure-communication-ui/chat/src/androidTest/java/com/azure/android/communication/ui/chat/ExampleInstrumentedTest.kt
  azure-communication-ui/chat/src/main/AndroidManifest.xml
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatComposite.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatCompositeException.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/locator/ServiceLocator.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/logger/DefaultLogger.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/logger/Logger.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/ChatCompositeLocalOptions.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/ChatCompositeParticipantViewData.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/package-info.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ChatCompositeActivity.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/AppStore.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/CommonTypes.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/Store.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/action/Action.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/middleware/ChatMiddleware.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/reducer/Reducer.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/state/ReduxState.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/service/ChatService.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/service/sdk/ChatSDKWrapper.kt
  azure-communication-ui/chat/src/test/java/com/azure/android/communication/ui/chat/ExampleUnitTest.kt
  azure-communication-ui/settings.gradle
Labels: Feature, Chat
