Repository Azure/communication-ui-library-android, pull requests merged in 2022-04, with the labels that each got.

#155 [Documentation] readme update
  README.md
  docs/UseCases.md
  docs/api/CallComposite/Reference.md
  docs/api/CallComposite/classes/CallComposite.md
  docs/api/CallComposite/classes/CallCompositeBuilder.md
  docs/api/CallComposite/classes/CallCompositeErrorCode.md
  docs/api/CallComposite/classes/CommunicationUIErrorCode.md
  docs/api/CallComposite/classes/CommunicationUIErrorEvent.md
  docs/api/CallComposite/classes/GroupCallOptions.md
  docs/api/CallComposite/classes/LanguageCode.md
  docs/api/CallComposite/classes/LocalizationConfiguration.md
  docs/api/CallComposite/classes/TeamsMeetingOptions.md
Labels: Documentation

#157 [Feature] Valid ACS Token test
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeACSTokenTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeAudioDeviceListTest.kt
Labels: Feature

#175 [Bug] Fix feature flags crash when application context is not Initialized
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/features/AdditionalFeatures.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/utilities/implementation/FeatureFlags.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
  azure-communication-ui/build.gradle
Labels: bug

#174 [Bug] Talkback should shift focus to Snackbar when it displays
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_control_bar_view.xml
Labels: bug

#192 [Config] Update Untranslated Strings
  azure-communication-ui/azure-communication-ui/src/main/res/values-de-rDE/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es-rES/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr-rFR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it-rIT/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja-rJP/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko-rKR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl-rNL/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru-rRU/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr-rTR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: Config

#187 [Bug] Language Dropdown Colour in Dark Mode
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/layout/language_dropdown_item.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values-night/colors.xml
Labels: bug

#196 [Refactor] Update strings file
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
Labels: Task, Config

#193 [Bug] Fixed focus highlight color for accessibility
  azure-communication-ui/azure-communication-ui/src/main/res/values-night/azure_communication_ui_colors.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_colors.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_themes.xml
Labels: bug

#180 [Feature] local participant persona avatar injection
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeJavaLauncher.java
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeKotlinLauncher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/views/AvatarImageSelectionLinearlayout.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/avatar_image_button_background.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/avatar_image_button_background_drawable.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_cat.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_fox.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_koala.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_monkey.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_mouse.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/drawable/image_octopus.png
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/layout/activity_settings.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/colors.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/strings.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/themes.xml
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/CallComposite.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/CallCompositeConfiguration.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/CommunicationUILocalDataOptions.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/di/DependencyInjectionContainer.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/persona/CommunicationUIPersonaData.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/DependencyInjectionContainerHolder.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/ViewModelFactory.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/localuser/LocalParticipantView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/localuser/LocalParticipantViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/common/audiodevicelist/AudioDeviceListView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/factories/CallingViewModelFactory.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/factories/SetupViewModelFactory.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupParticipantAvatarView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupParticipantAvatarViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/manager/AvatarViewManager.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/utilities/BottomCellItem.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/utilities/BottomCellViewHolder.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/localuser/LocalParticipantGridCellViewModelTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupParticipantAvatarViewModelUnitTest.kt
  docs/UseCases.md
  docs/api/CallComposite/Reference.md
  docs/api/CallComposite/classes/CommunicationUILocalDataOptions.md
  docs/api/CallComposite/classes/CommunicationUIPersonaData.md
Labels: Feature

#201 [Bug] Fixed banner link talkback
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/banner/BannerView.kt
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: bug

#194 [Bug] Added label for banner close button + removed double talkback for overlay
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_banner.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_lobby_overlay.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: bug

#199 [Feature] Handle call eviction
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CommunicationUIErrorCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/JoinCallButtonHolderViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/redux/state/CallingState.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/CallingService.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/sdk/CallingSDKEventHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/sdk/CallingStateWrapper.kt
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
Labels: Feature

#202 [Refactor] UI change for Leave call confirm
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingFragment.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/ConfirmLeaveOverlayView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/LeaveConfirmView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/LeaveConfirmViewModel.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/factories/CallingViewModelFactory.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/utilities/BottomCellItem.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/utilities/BottomCellViewHolder.kt
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_leave_confirm_dismiss_16_regular.xml
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_leave_confirm_telephone_21_10.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout-land/azure_communication_ui_call_fragment.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout-land/azure_communication_ui_call_leave_call_overlay.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout-sw600dp-land/azure_communication_ui_call_fragment.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_fragment.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_leave_call_overlay.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/LeaveConfirmViewModelUnitTest.kt
Labels: Task

#200 [Bug] leak audio session manager
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/manager/AccessibilityAnnouncementManager.kt
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: bug

#197 [Feature] Detect OS Locale and Refactor Public API
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeJavaLauncher.java
  azure-communication-ui/azure-communication-ui-demo-app/src/main/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeKotlinLauncher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/layout/activity_call_launcher.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/layout/activity_settings.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/menu/launcher_activity_action_bar.xml
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/strings.xml
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/CallComposite.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/AppLocalizationProvider.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LanguageCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LocalizationConfiguration.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LocalizationProvider.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/SupportLanguage.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/di/DependencyInjectionContainer.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/CallCompositeActivity.kt
Labels: Feature

#206 [Refactor] update fluent UI dependencies
  azure-communication-ui/build.gradle
Labels: Config

#211 [Documentation] Update localization docs
  docs/api/CallComposite/classes/LanguageCode.md
  docs/api/CallComposite/classes/LocalizationConfiguration.md
  docs/api/CallComposite/classes/SupportLanguage.md
Labels: Documentation

#215 [Documentation] Update README.md with Accessibility testing results
  README.md
Labels: Documentation

#219 [Bug] Leak Canary fix
  azure-communication-ui/azure-communication-ui-demo-app/build.gradle
Labels: bug

#218 [Bug] Text truncation issue on participant list fix
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/LeaveConfirmView.kt
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_bottom_drawer_cell.xml
  azure-communication-ui/azure-communication-ui/src/main/res/layout/azure_communication_ui_call_header.xml
Labels: bug
