Repository Azure/communication-ui-library-android, pull requests merged in 2022-09, with the labels that each got.

#409 [Feature][Calling] Device Manager error code refactoring
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorCode.kt
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/models/CallCompositeErrorCode.java
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/calling/src/testCalling/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
Labels: Feature, GA

#407 [Feature] Make Title a require field on the CallCompositeNavigationBarViewData
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui-demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeJavaLauncher.java
  azure-communication-ui/azure-communication-ui-demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeKotlinLauncher.kt
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/models/CallCompositeNavigationBarViewData.java
  azure-communication-ui/calling/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
  docs/CHANGELOG_UI.md
  docs/CHANGELOG_UI_CALLING.md
Labels: GA

#400 [BugFix] Correct talkback announcement for switching cameras
  azure-communication-ui/calling/src/main/res/layout/azure_communication_ui_calling_fragment_setup.xml
  azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-de/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-en-rGB/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-es/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-fr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-it/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ja/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ko/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-nl/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-pt/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ru/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-tr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/testCalling/java/com/azure/android/communication/ui/presentation/manager/AccessibilityAnnouncementManagerUnitTests.kt
Labels: bug

#420 [Calling][Bug] Network error in the setup screen
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoView.kt
Labels: GA

#422 [Calling][Feature] Update version name
  azure-communication-ui/build.gradle
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature, GA

#428 [Calling][Documentation] minor javadoc fixes
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeEventHandler.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeException.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeErrorCode.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalizationOptions.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeNavigationBarViewData.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeParticipantViewData.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRemoteOptions.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRemoteParticipantJoinedEvent.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeTeamsMeetingLinkLocator.java
Labels: GA

#431 [Chat][Feature] Localization API
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/ChatCompositeLocalizationOptions.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/ChatCompositeSupportedLocale.java
Labels: Chat

#432 [Calling][Refactor] Update strings
  azure-communication-ui/calling/src/main/res/values-de-rDE/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-de/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-en-rGB/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-en-rUS/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-es-rES/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-es/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-fr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-it-rIT/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-it/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ja/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ko/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-nl/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-pt/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-ru/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-tr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values-zh/azure_communication_ui_calling_strings.xml
  azure-communication-ui/calling/src/main/res/values/azure_communication_ui_calling_strings.xml
Labels: GA

#433 [Calling][Bug] camera stream is not visible to remote participant after call resume from background mode
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
Labels: GA

#427 [Chat][Code Style] Add ktlint and mock unit test for chat
  azure-communication-ui/chat/build.gradle
  azure-communication-ui/chat/src/test/java/com/azure/android/communication/ui/chat/locator/ServiceLocatorTest.kt
Labels: Chat

#435 [Calling][Bug] Wide screen crash fix
  azure-communication-ui/calling/src/main/res/layout-sw600dp/azure_communication_ui_calling_fragment_setup.xml
Labels: GA

#429 [Chat][Feature] Chat UI infrastructure
  azure-communication-ui/build.gradle
  azure-communication-ui/call-with-chat/build.gradle
  azure-communication-ui/calling/build.gradle
  azure-communication-ui/chat/build.gradle
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/ChatComposite.java
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ChatCompositeActivity.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/style/ChatCompositeChatTheme.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/chat/chatviewcomponents/ChatCompsiteActionBar.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/chat/screens/ChatCompositeChattingScreen.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/presentation/ui/container/ContainerView.kt
  azure-communication-ui/demo-app/build.gradle
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeJavaLauncher.java
Labels: Chat

#438 [Chat][Feature] Add Theme/ Strings Resource
  azure-communication-ui/chat/src/main/res/values-de-rDE/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-de/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-en-rGB/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-en-rUS/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-es-rES/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-es/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-fr-rFR/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-fr/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-it-rIT/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-it/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ja-rJP/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ja/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ko-rKR/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ko/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-nl-rNL/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-nl/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-pt-rBR/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-pt/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ru-rRU/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-ru/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-tr-rTR/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-tr/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-zh-rCN/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-zh-rTW/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values-zh/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values/azure_communication_ui_chat_colors.xml
  azure-communication-ui/chat/src/main/res/values/azure_communication_ui_chat_strings.xml
  azure-communication-ui/chat/src/main/res/values/azure_communication_ui_chat_theme_attrs.xml
  azure-communication-ui/chat/src/main/res/values/azure_communication_ui_chat_themes.xml
Labels: Chat

#450 [Calling][Bug] Video stream not send to remote after joining with video camera turned on
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
Labels: bug, GA

#465 [Feature] Adding chat & callwithchat declaration in github main readme
  README.md
Labels: GA
