Repository Azure/communication-ui-library-android, pull requests merged in 2022-05, with the labels that each got.

#208 [Refactor] Theme attributes name change
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui-demo-app/src/main/res/values/themes.xml
  azure-communication-ui/azure-communication-ui/src/main/res/color/azure_communication_ui_primary_selector.xml
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_cancel_leave_call_button.xml
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_speaking_rectangle_indicator.xml
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_speaking_rectangle_indicator_no_corner.xml
  azure-communication-ui/azure-communication-ui/src/main/res/drawable/azure_communication_ui_speaking_round_indicator.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_base_themes.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_calling_attr.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_theme_attrs.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_themes.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/public.xml
  docs/api/CallComposite/resources/AzureCommunicationUI.Theme.Calling.md
Labels: Task

#224 [Feature] OS Locale language support incase localization configuration is not provided
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/SupportLanguage.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/CallCompositeActivity.kt
Labels: Feature

#227 [Refactor] Change call eviction to use type CommunicationUIEventCode
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CommunicationUIErrorCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/events/CommunicationUIEventCode.java
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/CallStateError.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/service/calling/CallingService.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
Labels: Task

#216 [Bug] Talkback announce alerts
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/banner/BannerView.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/main/res/values-de-rDE/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rUS/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es-rES/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr-rFR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it-rIT/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja-rJP/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko-rKR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl-rNL/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru-rRU/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr-rTR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: bug

#225 [Refactor] Fix PermissionManager lint warnings
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/manager/PermissionManager.kt
Labels: Task

#220 [Bug] Fix crash with removal of camera permission while call ongoing
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/CallCompositeConfiguration.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/CallCompositeActivity.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/DependencyInjectionContainerHolder.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingFragment.kt
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/setup/SetupFragment.kt
Labels: bug

#235 [Refactor] Localization API update
  CHANGELOG.md
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/configuration/LocalizationConfiguration.java
  docs/api/CallComposite/classes/CommunicationUISupportedLocale.md
  docs/api/CallComposite/classes/LocalizationConfiguration.md
  docs/api/CallComposite/classes/SupportLanguage.md
Labels: Task

#236 [Feature] Small participant banner on tablet screens
  azure-communication-ui/azure-communication-ui/src/main/res/layout-sw600dp/azure_communication_ui_call_header.xml
Labels: Feature

#223 [Feature] Group participant name UI test case
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeBaselineUiTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeParticipantListTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/CallScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/RecyclerViewMatcher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/UiTestUtils.kt
Labels: Feature

#238 [Refactor] Fix deprecated unit test api
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/ACSBaseTestCoroutine.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/configuration/CallCompositeEventsHandlerTests.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/handler/RemoteParticipantHandlerUnitTests.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/helper/MainCoroutineRule.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/helper/StandardTestContextProvider.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/helper/UnconfinedTestContextProvider.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/banner/BannerViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/controlbar/ControlBarViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/lobby/LobbyOverlayViewModelTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/localuser/LocalParticipantGridCellViewModelTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridCellViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/AudioDeviceListViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/ErrorInfoViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/JoinCallButtonHolderViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/PermissionWarningViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/PreviewAreaViewViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupControlBarViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupGradientViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupParticipantAvatarViewModelUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/manager/AvatarViewManagerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/presentation/navigation/NavigationRouterUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/AppStoreUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/ErrorHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/test/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
Labels: Task

#237 [Bug] Audio device selection talkback fix
  azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/common/audiodevicelist/AudioDeviceListView.kt
  azure-communication-ui/azure-communication-ui/src/main/res/values-de-rDE/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-de/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rGB/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-en-rUS/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es-rES/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-es/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr-rFR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-fr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it-rIT/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-it/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja-rJP/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ja/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko-rKR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ko/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl-rNL/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-nl/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt-rBR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-pt/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru-rRU/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-ru/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr-rTR/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-tr/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rCN/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh-rTW/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values-zh/azure_communication_ui_strings.xml
  azure-communication-ui/azure-communication-ui/src/main/res/values/azure_communication_ui_strings.xml
Labels: bug

#242 [Refactor] Support UI test cases to run on any emulator and device
  azure-communication-ui/azure-communication-ui-demo-app/build.gradle
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/BaseUiTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeACSTokenTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeAudioDeviceListTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeBaselineUiTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeNetworkTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeParticipantListTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeTeamsUrlTest.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/matchers/BottomCellViewHolderMatcher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/CallScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/ScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/CallIdentifiersHelper.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/GetButtonTextAction.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/GetEditTextAction.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/NetworkUtils.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/RecyclerViewMatcher.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/RunWhenScreenOffOrLockedRule.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/TestFixture.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/UiTestUtils.kt
Labels: Refactor

#217 [Refactor] Handle error dialog during UI test run
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/CallScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/ScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SetupScreenRobot.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/GetTextViewAction.kt
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/UiTestUtils.kt
Labels: Task

#245 [Bug] Adjust Talkback sequence when snackbar is showing
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/azure-communication-ui/src/calling/res/layout/azure_communication_ui_calling_fragment_setup.xml
Labels: bug

#259 [Bug] show localization dropdown for Release variant
  azure-communication-ui/azure-communication-ui-demo-app/acs-ui-library.pro
  azure-communication-ui/scripts/installAab.sh
Labels: bug

#269 [Bug] Banner Talkback order change
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/banner/BannerView.kt
  azure-communication-ui/azure-communication-ui/src/calling/res/values-de-rDE/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-de/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-en-rGB/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-es-rES/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-es/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-fr-rFR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-fr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-it-rIT/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-it/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ja-rJP/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ja/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ko-rKR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ko/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-nl-rNL/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-nl/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-pt-rBR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-pt/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ru-rRU/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-ru/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-tr-rTR/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-tr/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh-rCN/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh-rTW/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values-zh/azure_communication_ui_calling_strings.xml
  azure-communication-ui/azure-communication-ui/src/calling/res/values/azure_communication_ui_calling_strings.xml
Labels: bug

#276 [Bug] Fix crash on Api21
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupFragment.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoView.kt
Labels: bug

#268 [Feature] Align call decline/deny with Call Eviction
  azure-communication-ui/azure-communication-ui-demo-app/src/androidTest/java/com/azure/android/communication/ui/callingcompositedemoapp/util/NetworkUtils.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/models/CommunicationUIEventCode.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/JoinCallButtonHolderViewModel.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/SetupControlBarViewModel.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/redux/state/CallingState.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/CallingService.kt
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/service/sdk/CallingStateWrapper.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/service/ErrorHandlerUnitTest.kt
  azure-communication-ui/azure-communication-ui/src/testCalling/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
Labels: Feature

#284 [Bug] Correct banner close button talkback
  azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/banner/BannerView.kt
  azure-communication-ui/azure-communication-ui/src/calling/res/layout/azure_communication_ui_calling_call_banner.xml
Labels: bug
