Repository Azure/communication-ui-library-android, pull requests merged in 2023-02, with the labels that each got.

#711 [Refactor][Chat] Updated Local User Logic
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/configuration/ChatCompositeEventHandlerRepository.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/MessageInfoModel.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/models/RemoteParticipantInfoModel.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/action/ParticipantAction.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/middleware/repository/MessageRepositoryMiddleware.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/middleware/sdk/ChatServiceListener.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/redux/reducer/ParticipantsReducer.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/service/sdk/ChatEventHandler.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/service/sdk/ChatFetchNotificationHandler.kt
  azure-communication-ui/chat/src/main/java/com/azure/android/communication/ui/chat/service/sdk/ChatSDKWrapper.kt
  azure-communication-ui/chat/src/test/java/com/azure/android/communication/ui/chat/redux/reducer/ParticipantsReducerUnitTest.kt
Labels: Refactor

#714 [Bugfix] Fixed TextField Layout
  azure-communication-ui/demo-app/src/chat/AndroidManifest.xml
  docs/CHANGELOG_UI_CHAT.md
Labels: bug

#710 [Feature][Calling] CSS call history
  azure-communication-ui/build.gradle
  azure-communication-ui/calling/build.gradle
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CallHistoryRepositoryTest.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeExtentions.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/data/CallHistoryRepository.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/data/DbHelper.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/data/model/CallHistoryRecordData.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallHistoryRecord.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeDebugInfo.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeDebugInfoExtensions.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/controlbar/more/MoreCallOptionsListViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/DebugInfoManager.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallingReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/CallingState.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallHistoryService.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/manager/DebugInfoManagerTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/reducer/CallingReducerUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/CallHistoryServiceTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
  azure-communication-ui/chat/src/androidTest/java/com/azure/android/communication/ui/chat/MessageViewTest.kt
  azure-communication-ui/demo-app/src/call-with-chat/java/com/azure/android/communication/ui/callwithchatdemoapp/CallWithChatLauncherActivity.kt
  azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeACSTokenTest.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivityErrorHandler.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/RemoteParticipantJoinedHandler.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeJavaLauncher.java
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeKotlinLauncher.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/launcher/CallingCompositeLauncher.java
  azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
Labels: Feature
