Repository Azure/communication-ui-library-android, pull requests merged in 2023-04, with the labels that each got.

#734 [Calling][Task] Addressing review comments
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/SetupViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/NavigationAction.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/AppStateReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/CallingReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/LocalParticipantReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/NavigationReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/LocalUserState.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/controlbar/ControlBarViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/setup/components/SetupControlBarViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/navigation/NavigationRouterUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/ErrorHandlerUnitTest.kt
Labels: Feature

#737 [Calling][Feature] Rooms v1
  azure-communication-ui/build.gradle
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallConfiguration.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeLocalOptions.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeParticipantRole.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeRoomLocator.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/ErrorInfoView.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
  azure-communication-ui/demo-app/build.gradle
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
  azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
  azure-communication-ui/demo-app/src/main/res/values/strings.xml
Labels: Feature

#740 [Calling][Feature] Changelog update for release
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature

#741 [Calling][Task] Readme update with release version
  azure-communication-ui/calling/README.md
Labels: Task

#743 [Documentation] CODEOWNERS update
  .github/CODEOWNERS
Labels: Documentation

#746 [Calling][Chat][Documentation] CODEOWNERS update for demo apps
  .github/CODEOWNERS
Labels: Documentation

#748 [Calling][Bug] skip setup should call call service call end when state is conencted
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingFragment.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmView.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/hangup/LeaveConfirmViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/factories/CallingViewModelFactory.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/hangup/LeaveConfirmViewModelUnitTest.kt
Labels: bug

#753 [Bug][Calling] on few devices audio is not delivered to remote participants
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/AudioModeManager.kt
Labels: bug

#758 [Calling][Bug] screen rotation not respecting Android device settings
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
Labels: bug

#750 [Calling][Feature] Dominant speakers
  azure-communication-ui/build.gradle
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/mocking/TestCallingSDK.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/RemoteParticipantHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/ParticipantInfoModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/participant/grid/ParticipantGridViewModel.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/action/ParticipantAction.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/middleware/handler/CallingMiddlewareActionHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/AudioSessionReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/LifecycleReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/NavigationReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/reducer/ParticipantReducer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/AppReduxState.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/redux/state/RemoteParticipantsState.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/CallingService.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDK.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKEventHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/CallingSDKWrapper.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/DominantSpeakersInfoWrapper.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/service/sdk/TypeConversions.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/handler/RemoteParticipantHandlerUnitTests.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/header/InfoHeaderViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridCellViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/ParticipantGridViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/participantlist/ParticipantListViewModelUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/manager/AccessibilityAnnouncementManagerUnitTests.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/manager/AvatarViewManagerUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/AppStoreUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/middleware/handler/CallingMiddlewareActionHandlerUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/reducer/AppReduxStateReducerUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/redux/reducer/ParticipantInfoModelStateReducerUnitTest.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/CallingServiceUnitTests.kt
Labels: Feature, Draft

#762 [Calling][Feature] public api for call state change and end composite
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CallStateEventsTest.kt
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/CompositeExitAPITest.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainerImpl.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorCode.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallStateCode.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallStateEvent.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeExitEvent.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/manager/CompositeExitManager.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/handler/CallStateHandlerUnitTests.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/manager/CompositeExitManagerUnitTests.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/views/EndCompositeButtonView.kt
  azure-communication-ui/demo-app/src/calling/res/layout/activity_call_launcher.xml
  azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
  azure-communication-ui/demo-app/src/main/res/layout/end_composite_button.xml
  azure-communication-ui/demo-app/src/main/res/values/strings.xml
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature
