Repository Azure/communication-ui-library-android, pull requests merged in 2023-08, with the labels that each got.

#811 [Calling][Bug] pix pip crash for Android API 26 (few Samsung devices)
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
Labels: bug

#804 [Calling][Feature] Orientation API implementation
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallCompositeBuilder.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/CallCompositeConfiguration.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeSupportedScreenOrientation.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/CallCompositeActivity.kt
  azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/CallingCompositeScreenOrientationTest.kt
  azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/HomeScreenRobot.kt
  azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/robots/SettingsScreenRobot.kt
  azure-communication-ui/demo-app/src/calling-test/java/com/azure/android/communication/ui/callingcompositedemoapp/util/TestFixture.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/features/SettingsFeatures.kt
  azure-communication-ui/demo-app/src/calling/res/layout/activity_settings.xml
  azure-communication-ui/demo-app/src/main/res/layout/screen_orientation_dropdown_item.xml
  azure-communication-ui/demo-app/src/main/res/values/strings.xml
Labels: Feature

#812 [Calling] update version for 1.5.0 alpha 5
  azure-communication-ui/build.gradle
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/DiagnosticConfig.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/service/calling/DiagnosticConfigUnitTests.kt
Labels: Refactor

#814 [Calling][Feature] callstatechange exitcomposite api merge
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/CallComposite.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/configuration/events/CallCompositeEventsHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/di/DependencyInjectionContainer.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorCode.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/error/ErrorHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/handlers/CallStateHandler.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeCallStateChangedEvent.java
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/models/CallCompositeDismissedEvent.java
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/handler/CallStateHandlerUnitTests.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherActivity.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallLauncherViewModel.kt
  azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/SettingsActivity.kt
  docs/CHANGELOG_UI_CALLING.md
Labels: Feature

#824 [Calling][Bug] Hide lobby participants on grid view and participant list.
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/BaseUiTest.kt
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/Utils.kt
  azure-communication-ui/calling/src/androidTest/java/com/azure/android/communication/ui/calling/LobbyParticipantsVisibilityTest.kt
  azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/calling/CallingViewModel.kt
  azure-communication-ui/calling/src/test/java/com/azure/android/communication/ui/presentation/fragment/calling/CallingViewModelUnitTest.kt
Labels: bug
